# Generated by Django 3.2.14 on 2022-07-12 12:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 15, 37, 28, 628996), verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 15, 37, 28, 628996), verbose_name='актуальность ключа'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 15, 37, 28, 628996), verbose_name='время регистрации'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('17a53b20-7742-4613-889a-6c6ed979eafa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
