# Generated by Django 3.2.14 on 2022-07-11 12:15

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 15, 15, 4, 598606), verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 15, 15, 4, 582979), verbose_name='актуальность ключа'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 15, 15, 4, 582979), verbose_name='время регистрации'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6fbb7c38-e36d-4052-ab29-6444b8c52501'), primary_key=True, serialize=False),
        ),
    ]
