# Generated by Django 3.2.14 on 2022-07-11 12:20

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220711_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 15, 20, 21, 12808), verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 15, 20, 21, 8806), verbose_name='актуальность ключа'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='email',
            field=models.CharField(max_length=128, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 15, 20, 21, 8806), verbose_name='время регистрации'),
        ),
        migrations.AlterField(
            model_name='habruser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('85aa5c65-7e4a-47e8-982e-6c78b2fe1dda'), editable=False, primary_key=True, serialize=False),
        ),
    ]
